In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
dataset = pd.read_csv('/content/winequality-red.csv')

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [ ]:
X = dataset.iloc[:,1:-1].values
y = dataset.iloc[:,-1].values

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [ ]:
l_cla = LogisticRegression()
k_cla = KNeighborsClassifier()
d_cla = DecisionTreeClassifier()
r_cla = RandomForestClassifier()
s_cla = SVC(kernel='linear')
ks_cla= SVC(kernel='rbf')

In [ ]:
l_cla.fit(X_train, y_train)
k_cla.fit(X_train, y_train)
d_cla.fit(X_train, y_train)
r_cla.fit(X_train, y_train)
s_cla.fit(X_train, y_train)
ks_cla.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
l_pred = l_cla.predict(X_test)
k_pred = k_cla.predict(X_test)
d_pred = d_cla.predict(X_test)
r_pred = r_cla.predict(X_test)
s_pred = s_cla.predict(X_test)
ks_pred = ks_cla.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
l_c = confusion_matrix(y_test,l_pred)
k_c = confusion_matrix(y_test, k_pred)
d_c = confusion_matrix(y_test, d_pred)
r_c = confusion_matrix(y_test, r_pred)
s_c = confusion_matrix(y_test, s_pred)
ks_c = confusion_matrix(y_test, ks_pred)


In [ ]:
l_c

array([[ 0,  1,  0,  0,  0,  0],
       [ 0,  0,  5,  2,  0,  0],
       [ 0,  0, 95, 31,  2,  0],
       [ 0,  1, 49, 77,  4,  0],
       [ 0,  0,  4, 38,  9,  0],
       [ 0,  0,  0,  2,  0,  0]])

In [ ]:
k_c

array([[ 0,  1,  0,  0,  0,  0],
       [ 0,  1,  4,  2,  0,  0],
       [ 0,  2, 90, 35,  1,  0],
       [ 0,  0, 49, 78,  4,  0],
       [ 0,  0,  8, 27, 16,  0],
       [ 0,  0,  0,  1,  1,  0]])

In [ ]:
d_c

array([[ 0,  0,  1,  0,  0,  0],
       [ 0,  1,  4,  2,  0,  0],
       [ 0,  4, 97, 23,  4,  0],
       [ 0,  3, 33, 81, 14,  0],
       [ 0,  0,  6, 12, 33,  0],
       [ 0,  0,  0,  0,  1,  1]])

In [ ]:
r_c

array([[  0,   0,   1,   0,   0,   0],
       [  0,   0,   7,   0,   0,   0],
       [  0,   0, 113,  15,   0,   0],
       [  0,   1,  31,  94,   5,   0],
       [  0,   0,   2,  23,  26,   0],
       [  0,   0,   0,   0,   1,   1]])

In [ ]:
s_c

array([[ 0,  0,  1,  0,  0,  0],
       [ 0,  0,  5,  2,  0,  0],
       [ 0,  0, 94, 34,  0,  0],
       [ 0,  0, 50, 81,  0,  0],
       [ 0,  0,  4, 47,  0,  0],
       [ 0,  0,  0,  2,  0,  0]])

In [ ]:
ks_c

array([[  0,   0,   1,   0,   0,   0],
       [  0,   0,   6,   1,   0,   0],
       [  0,   0, 105,  23,   0,   0],
       [  0,   0,  44,  85,   2,   0],
       [  0,   0,   5,  37,   9,   0],
       [  0,   0,   0,   1,   1,   0]])

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
l_a = accuracy_score(y_test, l_pred)
k_a = accuracy_score(y_test, k_pred)
d_a = accuracy_score(y_test, d_pred)
r_a = accuracy_score(y_test, r_pred)
s_a = accuracy_score(y_test, s_pred)
ks_a = accuracy_score(y_test, ks_pred)

In [ ]:
print('Logistic Regression: ' + str(l_a) + '\\nKNN: ' + str(k_a) + '\\nDecision Tree: ' + str(d_a) + '\\nRandom Forest: ' + str(r_a) + '\\nLinear SVC: ' + str(s_a) + '\\nKernel SVC: ' + str(l_a))

Logistic Regression: 0.565625\nKNN: 0.578125\nDecision Tree: 0.665625\nRandom Forest: 0.73125\nLinear SVC: 0.546875\nKernel SVC: 0.565625
